engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 90
exclude_paths:
- "frontend/static/bootstrap.min.js"
- "frontend/static/holder.js"
- "frontend/static/jquery.min.js"
ratings:
  paths:
  - "api/**/*"
  - "frontend/**/*"
