version: "2"

services:

    nginx:
        image: nginx:1.13
        ports:
            - "8005:80"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./html:/usr/share/nginx/html:ro

    api:
        image: jlabusch/wrms-dash-api
        build: app
        ports:
            - "8004:80"
        entrypoint:
            - npm
            - start
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./app/index.js:/opt/index.js:ro

