version: "2"

services:

    nginx:
        image: nginx:1.13
        restart: always
        ports:
            - "8005:80"
        links:
            - frontend
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro

    frontend:
        image: jlabusch/wrms-dash-frontend
        build: django-frontend
        expose:
            - "80"
        environment:
            - DJANGO_DEBUG=True
            - DJANGO_BACKEND_URI=http://api:80
            - DJANGO_SECRET
        links:
            - api
        volumes:
            - /etc/localtime:/etc/localtime:ro

    api:
        image: jlabusch/wrms-dash-api
        build: app
        expose:
            - "80"
        entrypoint:
            - npm
            - start
        environment:
            - ICINGA_BASIC_AUTH
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./app/config/default.json:/opt/config/default.json:ro

